export enum BookingStatus {
  BookingPending = "Booking Pending",
  BookingConfirmed = "Booking Confirmed",
  DriverAssigned = "Driver Assigned",
  DriverEnRoute = "Driver En Route",
  CarPickedUp = "Car Picked Up",
  CarArrivedAtServiceCenter = "Car Arrived at Service Center",
  ServiceInProgress = "Service In Progress",
  ServiceCompleted = "Service Completed",
  CarEnRouteBack = "Car En Route Back",
  CarDelivered = "Car Delivered",
  ReadyForPickup = "Ready for Pickup",
  BookingCompleted = "Booking Completed",
  BookingCancelled = "Booking Cancelled",
}
