export const baseOrderUrl = 'http://localhost:3003/api/order'
export const baseUserUrl = 'http://localhost:3000/api/user'
export const baseCompanyUrl = 'http://localhost:3001/api/company'
export const baseAdminUrl = 'http://localhost:3002/api/admin'
export const baseChatUrl = 'http://localhost:3002/api/chat'