apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: alimiyn/car-service-booking:latest
          ports:
            - containerPort: 3003
            - containerPort: 6004
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  type: ClusterIP
  selector:
    app: booking
  ports:
    - name: http
      port: 3003
      targetPort: 3003
    - name: grpc-6004
      port: 6004
      targetPort: 6004