apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: alimiyn/car-service-company:latest
          ports:
            - containerPort: 3001
            - containerPort: 6001
            - containerPort: 6002
            - containerPort: 6003
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
spec:
  type: ClusterIP
  selector:
    app: company
  ports:
    - name: http
      port: 3001
      targetPort: 3001
    - name: grpc-6001
      port: 6001
      targetPort: 6001
    - name: grpc-6002
      port: 6002
      targetPort: 6002
    - name: grpc-6003
      port: 6003
      targetPort: 6003